Changed American Spelling to British
lumsx/edx-platform pull request #42
Opened 2021-02-24 21:44 UTC by mumerfarooq000

Changed the words Enrollment, Enroll, and Honor

2021-03-01 14:29 UTC, emzubair approved these changes
LGTM
All these changes are the core changes, will face issue while updating to the next release.

2021-03-01 16:10 UTC, tasawernawaz requested changes
@mumerfarooq000 please revert all changes in `/i18n/*` and `locale`. We don't do changes in language files directly. The translation process is totally different and these files are autogenerated with commands.

2021-03-01 16:10 UTC, tasawernawaz commented on cms/envs/common.py
> +    # 'django_cookies_samesite.middleware.CookiesSameSite',
why this change was required?

2021-03-01 16:10 UTC, tasawernawaz commented on lms/envs/common.py
> +    # 'django_cookies_samesite.middleware.CookiesSameSite',
same here

2021-03-01 16:11 UTC, tasawernawaz commented
also please add a link to the ticket in the description of the PR.

2021-03-10 11:23 UTC, sheralim012 approved these changes

2021-03-10 11:23 UTC, merged